### ISSUE TITLE
Fails to implement the OAUTH branch.

### ISSUE THREAD

**Issue by odidev** [oktadeveloper/spring-boot-microservices-example#71] opened 2023-05-12 06:45 UTC
Hi, 

I have tried to test the `OAUTH` branch by using [this](https://developer.okta.com/blog/2018/02/13/secure-spring-microservices-with-oauth) document. After running the `./run.sh` command, all the application is up and running.  

![Screenshot (511)](https://github.com/oktadev/spring-boot-microservices-example/assets/40816837/86383b82-eecc-456c-94a4-155d4d64a07e)

When I tried to access `https//localhost:8081/good-beers` an OKTA sign-in page popped up. After successful login, I can see a list of good-beers.  

But when I tried to access` https://localhost:8081/home` ,it gave me the error **"Invalid token does not contain resource id (oauth2-resource)"** 
 
![Screenshot (512)](https://github.com/oktadev/spring-boot-microservices-example/assets/40816837/775568da-4fc3-479e-bb12-15cfe2049763)

Can you please provide me with some pointers here?

**Comment by mraible** [comment] 2023-05-16 20:29
Hello @odidev,

This is a pretty old example from February 2018. The blog post you linked to suggests you go to a newer version at https://developer.okta.com/blog/2019/05/22/java-microservices-spring-boot-spring-cloud. Is there a particular reason you want to use this version?

**Comment by mraible** [comment] 2023-05-17 16:39
I was able to get everything working today. I did have to use Java 8. I followed the instructions in the README and modified the following files to contain my OIDC app's information.

```
beer-catalog-service/src/main/resources/application.properties
client/src/app/shared/okta/okta.service.ts
edge-service/src/main/resources/application.properties
```

The one thing that tripped me up is I didn't have a `roles` claim defined. The stack trace in my terminal helped me track down the issue. I added it on Okta.

<img width="1050" alt="Screenshot 2023-05-17 at 10 34 40 AM" src="https://github.com/oktadev/spring-boot-microservices-example/assets/17892/a0702e99-8071-4c2d-96eb-f2eabadcc2a2">

Then, `http://localhost:8081/home` works as expected. 

<img width="1102" alt="Screenshot 2023-05-17 at 10 34 19 AM" src="https://github.com/oktadev/spring-boot-microservices-example/assets/17892/70c950b7-a5c4-4c8f-a61b-3fafee2308b6">

I'll close this issue since I'm not able to reproduce it. Please re-open if you're still having issues.

**Closed as completed by mraible** 2023-05-17 16:39 UTC
